# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# load in default scene and lines
scene = Scene.create(title: 'Henry IV, Part One', description: 'SCENE IV. The Boar\'s-Head Tavern, Eastcheap.')

# load in lines
scene_id = scene.id
lines = [
  {character: '', line: "Enter PRINCE HENRY and POINS", line_order: 5, scene_id: scene_id}, 
  {character: 'PRINCE HENRY', line: "Ned, prithee, come out of that fat room, and lend me\nthy hand to laugh a little.", line_order: 10, scene_id: scene_id}, 
  {character: 'POINS', line: "Where hast been, Hal?", line_order: 15, scene_id: scene_id}, 
  {character: 'PRINCE HENRY', line: "With three or four loggerheads amongst three or four\nscore hogsheads. I have sounded the very\nbase-string of humility. Sirrah, I am sworn brother\nto a leash of drawers; and can call them all by\ntheir christen names, as Tom, Dick, and Francis.\nThey take it already upon their salvation, that\nthough I be but the prince of Wales, yet I am king\nof courtesy; and tell me flatly I am no proud Jack,\nlike Falstaff, but a Corinthian, a lad of mettle, a\ngood boy, by the Lord, so they call me, and when I\nam king of England, I shall command all the good\nlads in Eastcheap. They call drinking deep, dyeing\nscarlet; and when you breathe in your watering, they\ncry  'hem!' and bid you play it off. To conclude, I\nam so good a proficient in one quarter of an hour,\nthat I can drink with any tinker in his own language\nduring my life. I tell thee, Ned, thou hast lost\nmuch honour, that thou wert not with me in this sweet\naction. But, sweet Ned,--to sweeten which name of\nNed, I give thee this pennyworth of sugar, clapped\neven now into my hand by an under-skinker, one that\nnever spake other English in his life than 'Eight\nshillings and sixpence' and 'You are welcome,' with\nthis shrill addition, 'Anon, anon, sir! Score a pint\nof bastard in the Half-Moon,' or so. But, Ned, to\ndrive away the time till Falstaff come, I prithee,\ndo thou stand in some by-room, while I question my\npuny drawer to what end he gave me the sugar; and do\nthou never leave calling 'Francis,' that his tale\nto me may be nothing but 'Anon.' Step aside, and\nI'll show thee a precedent.\n", line_order: 20, scene_id: scene_id},
  {character: 'POINS', line: "Francis!\n", line_order: 25, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Thou art perfect.\n", line_order: 30, scene_id: scene_id},
  {character: 'POINS', line: "Francis!", line_order: 35, scene_id: scene_id},
  {character: '', line: "Exit POINS", line_order: 40, scene_id: scene_id},
  {character: '', line: "Enter FRANCIS", line_order: 45, scene_id: scene_id},
  {character: 'FRANCIS', line: "Anon, anon, sir. Look down into the Pomgarnet, Ralph.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Come hither, Francis.\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "My lord?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "How long hast thou to serve, Francis?\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Forsooth, five years, and as much as to--\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "[Within]  Francis!\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Anon, anon, sir.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Five year! by'r lady, a long lease for the clinking\nof pewter. But, Francis, darest thou be so valiant\nas to play the coward with thy indenture and show it\na fair pair of heels and run from it?\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "O Lord, sir, I'll be sworn upon all the books in\nEngland, I could find in my heart.\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "[Within]  Francis!\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Anon, sir.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "How old art thou, Francis?\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Let me see--about Michaelmas next I shall be--\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "[Within]  Francis!\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Anon, sir. Pray stay a little, my lord.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Nay, but hark you, Francis: for the sugar thou\ngavest me,'twas a pennyworth, wast't not?\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "O Lord, I would it had been two!\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I will give thee for it a thousand pound: ask me\nwhen thou wilt, and thou shalt have it.\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "[Within]  Francis!\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Anon, anon.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Anon, Francis? No, Francis; but to-morrow, Francis;\nor, Francis, o' Thursday; or indeed, Francis, when\nthou wilt. But, Francis!\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "My lord?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Wilt thou rob this leathern jerkin, crystal-button,\nnot-pated, agate-ring, puke-stocking, caddis-garter,\nsmooth-tongue, Spanish-pouch,--\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "O Lord, sir, who do you mean?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Why, then, your brown bastard is your only drink;\nfor look you, Francis, your white canvas doublet\nwill sully: in Barbary, sir, it cannot come to so much.\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "What, sir?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "[Within]  Francis!\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Away, you rogue! dost thou not hear them call?\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Here they both call him; the drawer stands amazed, not knowing which way to go", line_order: 40, scene_id: scene_id},
  {character: '', line: "Enter Vintner", line_order: 40, scene_id: scene_id},
  {character: 'Vintner', line: "What, standest thou still, and hearest such a\ncalling? Look to the guests within.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exit Francis", line_order: 5, scene_id: scene_id},
  {character: 'Vintner', line: "My lord, old Sir John, with half-a-dozen more, are\nat the door: shall I let them in?", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Let them alone awhile, and then open the door.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exit Vintner", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Poins!", line_order: 5, scene_id: scene_id},
  {character: '', line: "Re-enter POINS", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Anon, anon, sir.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Sirrah, Falstaff and the rest of the thieves are at\nthe door: shall we be merry?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "As merry as crickets, my lad. But hark ye; what\ncunning match have you made with this jest of the\ndrawer? come, what's the issue?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I am now of all humours that have showed themselves\nhumours since the old days of goodman Adam to the\npupil age of this present twelve o'clock at midnight.", line_order: 5, scene_id: scene_id},
  {character: '', line: "Re-enter FRANCIS", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What's o'clock, Francis?\n", line_order: 5, scene_id: scene_id},
  {character: 'FRANCIS', line: "Anon, anon, sir.", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exit", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "That ever this fellow should have fewer words than a\nparrot, and yet the son of a woman! His industry is\nupstairs and downstairs; his eloquence the parcel of\na reckoning. I am not yet of Percy's mind, the\nHotspur of the north; he that kills me some six or\nseven dozen of Scots at a breakfast, washes his\nhands, and says to his wife 'Fie upon this quiet\nlife! I want work.' 'O my sweet Harry,' says she,\n'how many hast thou killed to-day?' 'Give my roan\nhorse a drench,' says he; and answers 'Some\nfourteen,' an hour after; 'a trifle, a trifle.' I\nprithee, call in Falstaff: I'll play Percy, and\nthat damned brawn shall play Dame Mortimer his\nwife. 'Rivo!' says the drunkard. Call in ribs, call in tallow.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Enter FALSTAFF, GADSHILL, BARDOLPH, and PETO; FRANCIS following with wine", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Welcome, Jack: where hast thou been?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "A plague of all cowards, I say, and a vengeance too!\nmarry, and amen! Give me a cup of sack, boy. Ere I\nlead this life long, I'll sew nether stocks and mend\nthem and foot them too. A plague of all cowards!\nGive me a cup of sack, rogue. Is there no virtue extant?\nHe drinks", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Didst thou never see Titan kiss a dish of butter?\npitiful-hearted Titan, that melted at the sweet tale\nof the sun's! if thou didst, then behold that compound.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "You rogue, here's lime in this sack too: there is\nnothing but roguery to be found in villanous man:\nyet a coward is worse than a cup of sack with lime\nin it. A villanous coward! Go thy ways, old Jack;\ndie when thou wilt, if manhood, good manhood, be\nnot forgot upon the face of the earth, then am I a\nshotten herring. There live not three good men\nunhanged in England; and one of them is fat and\ngrows old: God help the while! a bad world, I say.\nI would I were a weaver; I could sing psalms or any\nthing. A plague of all cowards, I say still.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "How now, wool-sack! what mutter you?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "A king's son! If I do not beat thee out of thy\nkingdom with a dagger of lath, and drive all thy\nsubjects afore thee like a flock of wild-geese,\nI'll never wear hair on my face more. You Prince of Wales!\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Why, you whoreson round man, what's the matter?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Are not you a coward? answer me to that: and Poins there?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "'Zounds, ye fat paunch, an ye call me coward, by the\nLord, I'll stab thee.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "I call thee coward! I'll see thee damned ere I call\nthee coward: but I would give a thousand pound I\ncould run as fast as thou canst. You are straight\nenough in the shoulders, you care not who sees your\nback: call you that backing of your friends? A\nplague upon such backing! give me them that will\nface me. Give me a cup of sack: I am a rogue, if I\ndrunk to-day.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "O villain! thy lips are scarce wiped since thou\ndrunkest last.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "All's one for that.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "He drinks", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "A plague of all cowards, still say I.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What's the matter?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "What's the matter! there be four of us here have\nta'en a thousand pound this day morning.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Where is it, Jack? where is it?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Where is it! taken from us it is: a hundred upon\npoor four of us.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What, a hundred, man?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "I am a rogue, if I were not at half-sword with a\ndozen of them two hours together. I have 'scaped by\nmiracle. I am eight times thrust through the\ndoublet, four through the hose; my buckler cut\nthrough and through; my sword hacked like a\nhand-saw--ecce signum! I never dealt better since\nI was a man: all would not do. A plague of all\ncowards! Let them speak: if they speak more or\nless than truth, they are villains and the sons of darkness.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Speak, sirs; how was it?\n", line_order: 5, scene_id: scene_id},
  {character: 'GADSHILL', line: "We four set upon some dozen--\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Sixteen at least, my lord.\n", line_order: 5, scene_id: scene_id},
  {character: 'GADSHILL', line: "And bound them.\n", line_order: 5, scene_id: scene_id},
  {character: 'PETO', line: "No, no, they were not bound.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "You rogue, they were bound, every man of them; or I\nam a Jew else, an Ebrew Jew.\n", line_order: 5, scene_id: scene_id},
  {character: 'GADSHILL', line: "As we were sharing, some six or seven fresh men set upon us--\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "And unbound the rest, and then come in the other.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What, fought you with them all?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "All! I know not what you call all; but if I fought\nnot with fifty of them, I am a bunch of radish: if\nthere were not two or three and fifty upon poor old\nJack, then am I no two-legged creature.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Pray God you have not murdered some of them.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Nay, that's past praying for: I have peppered two\nof them; two I am sure I have paid, two rogues\nin buckram suits. I tell thee what, Hal, if I tell\nthee a lie, spit in my face, call me horse. Thou\nknowest my old ward; here I lay and thus I bore my\npoint. Four rogues in buckram let drive at me--\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What, four? thou saidst but two even now.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Four, Hal; I told thee four.\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Ay, ay, he said four.\n", line_order: 5, scene_id: scene_id},  
  {character: 'FALSTAFF', line: "These four came all a-front, and mainly thrust at\nme. I made me no more ado but took all their seven\npoints in my target, thus.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Seven? why, there were but four even now.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "In buckram?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Ay, four, in buckram suits.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Seven, by these hilts, or I am a villain else.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Prithee, let him alone; we shall have more anon.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Dost thou hear me, Hal?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Ay, and mark thee too, Jack.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Do so, for it is worth the listening to. These nine\nin buckram that I told thee of--\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "So, two more already.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Their points being broken,--\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Down fell their hose.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Began to give me ground: but I followed me close,\ncame in foot and hand; and with a thought seven of\nthe eleven I paid.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "O monstrous! eleven buckram men grown out of two!\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "But, as the devil would have it, three misbegotten\nknaves in Kendal green came at my back and let drive\nat me; for it was so dark, Hal, that thou couldst\nnot see thy hand.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "These lies are like their father that begets them;\ngross as a mountain, open, palpable. Why, thou\nclay-brained guts, thou knotty-pated fool, thou\nwhoreson, obscene, grease tallow-catch,--\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "What, art thou mad? art thou mad? is not the truth\nthe truth?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Why, how couldst thou know these men in Kendal\ngreen, when it was so dark thou couldst not see thy\nhand? come, tell us your reason: what sayest thou to this?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Come, your reason, Jack, your reason.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "What, upon compulsion? 'Zounds, an I were at the\nstrappado, or all the racks in the world, I would\nnot tell you on compulsion. Give you a reason on\ncompulsion! If reasons were as plentiful as\nblackberries, I would give no man a reason upon\ncompulsion, I.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I'll be no longer guilty of this sin; this sanguine\ncoward, this bed-presser, this horseback-breaker,\nthis huge hill of flesh,--\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "'Sblood, you starveling, you elf-skin, you dried\nneat's tongue, you bull's pizzle, you stock-fish! O\nfor breath to utter what is like thee! you\ntailor's-yard, you sheath, you bowcase; you vile\nstanding-tuck,--\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Well, breathe awhile, and then to it again: and\nwhen thou hast tired thyself in base comparisons,\nhear me speak but this.\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Mark, Jack.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "We two saw you four set on four and bound them, and\nwere masters of their wealth. Mark now, how a plain\ntale shall put you down. Then did we two set on you\nfour; and, with a word, out-faced you from your\nprize, and have it; yea, and can show it you here in\nthe house: and, Falstaff, you carried your guts\naway as nimbly, with as quick dexterity, and roared\nfor mercy and still run and roared, as ever I heard\nbull-calf. What a slave art thou, to hack thy sword\nas thou hast done, and then say it was in fight!\nWhat trick, what device, what starting-hole, canst\nthou now find out to hide thee from this open and\napparent shame?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "Come, let's hear, Jack; what trick hast thou now?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "By the Lord, I knew ye as well as he that made ye.\nWhy, hear you, my masters: was it for me to kill the\nheir-apparent? should I turn upon the true prince?\nwhy, thou knowest I am as valiant as Hercules: but\nbeware instinct; the lion will not touch the true\nprince. Instinct is a great matter; I was now a\ncoward on instinct. I shall think the better of\nmyself and thee during my life; I for a valiant\nlion, and thou for a true prince. But, by the Lord,\nlads, I am glad you have the money. Hostess, clap\nto the doors: watch to-night, pray to-morrow.\nGallants, lads, boys, hearts of gold, all the titles\nof good fellowship come to you! What, shall we be\nmerry? shall we have a play extempore?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Content; and the argument shall be thy running away.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Ah, no more of that, Hal, an thou lovest me!\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Enter Hostess", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "O Jesu, my lord the prince!\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "How now, my lady the hostess! what sayest thou to\nme?\n", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "Marry, my lord, there is a nobleman of the court at\ndoor would speak with you: he says he comes from\nyour father.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Give him as much as will make him a royal man, and\nsend him back again to my mother.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "What manner of man is he?\n", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "An old man.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "What doth gravity out of his bed at midnight? Shall\nI give him his answer?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Prithee, do, Jack.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "'Faith, and I'll send him packing.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exit FALSTAFF", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Now, sirs: by'r lady, you fought fair; so did you,\nPeto; so did you, Bardolph: you are lions too, you\nran away upon instinct, you will not touch the true\nprince; no, fie!\n", line_order: 5, scene_id: scene_id},
  {character: 'BARDOLPH', line: "'Faith, I ran when I saw others run.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "'Faith, tell me now in earnest, how came Falstaff's\nsword so hacked?\n", line_order: 5, scene_id: scene_id},
  {character: 'PETO', line: "Why, he hacked it with his dagger, and said he would\nswear truth out of England but he would make you\nbelieve it was done in fight, and persuaded us to do the like.\n", line_order: 5, scene_id: scene_id},
  {character: 'BARDOLPH', line: "Yea, and to tickle our noses with spear-grass to\nmake them bleed, and then to beslubber our garments\nwith it and swear it was the blood of true men. I\ndid that I did not this seven year before, I blushed\nto hear his monstrous devices.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "O villain, thou stolest a cup of sack eighteen years\nago, and wert taken with the manner, and ever since\nthou hast blushed extempore. Thou hadst fire and\nsword on thy side, and yet thou rannest away: what\ninstinct hadst thou for it?\n", line_order: 5, scene_id: scene_id},
  {character: 'BARDOLPH', line: "My lord, do you see these meteors? do you behold\nthese exhalations?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I do.\n", line_order: 5, scene_id: scene_id},
  {character: 'BARDOLPH', line: "What think you they portend?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Hot livers and cold purses.\n", line_order: 5, scene_id: scene_id},
  {character: 'BARDOLPH', line: "Choler, my lord, if rightly taken.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "No, if rightly taken, halter.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Re-enter FALSTAFF", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Here comes lean Jack, here comes bare-bone.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "How now, my sweet creature of bombast!\nHow long is't ago, Jack, since thou sawest thine own knee?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "My own knee! when I was about thy years, Hal, I was\nnot an eagle's talon in the waist; I could have\ncrept into any alderman's thumb-ring: a plague of\nsighing and grief! it blows a man up like a\nbladder. There's villanous news abroad: here was\nSir John Bracy from your father; you must to the\ncourt in the morning. That same mad fellow of the\nnorth, Percy, and he of Wales, that gave Amamon the\nbastinado and made Lucifer cuckold and swore the\ndevil his true liegeman upon the cross of a Welsh\nhook--what a plague call you him?\n", line_order: 5, scene_id: scene_id},
  {character: 'POINS', line: "O, Glendower.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Owen, Owen, the same; and his son-in-law Mortimer,\nand old Northumberland, and that sprightly Scot of\nScots, Douglas, that runs o' horseback up a hill\nperpendicular,--\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "He that rides at high speed and with his pistol\nkills a sparrow flying.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "You have hit it.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "So did he never the sparrow.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Well, that rascal hath good mettle in him; he will not run.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Why, what a rascal art thou then, to praise him so\nfor running!\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "O' horseback, ye cuckoo; but afoot he will not budge a foot.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Yes, Jack, upon instinct.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "I grant ye, upon instinct. Well, he is there too,\nand one Mordake, and a thousand blue-caps more:\nWorcester is stolen away to-night; thy father's\nbeard is turned white with the news: you may buy\nland now as cheap as stinking mackerel.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Why, then, it is like, if there come a hot June and\nthis civil buffeting hold, we shall buy maidenheads\nas they buy hob-nails, by the hundreds.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "By the mass, lad, thou sayest true; it is like we\nshall have good trading that way. But tell me, Hal,\nart not thou horrible afeard? thou being\nheir-apparent, could the world pick thee out three\nsuch enemies again as that fiend Douglas, that\nspirit Percy, and that devil Glendower? Art thou\nnot horribly afraid? doth not thy blood thrill at\nit?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Not a whit, i' faith; I lack some of thy instinct.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Well, thou wert be horribly chid tomorrow when thou\ncomest to thy father: if thou love me, practise an answer.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Do thou stand for my father, and examine me upon the\nparticulars of my life.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Shall I? content: this chair shall be my state,\nthis dagger my sceptre, and this cushion my crown.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Thy state is taken for a joined-stool, thy golden\nsceptre for a leaden dagger, and thy precious rich\ncrown for a pitiful bald crown!\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Well, an the fire of grace be not quite out of thee,\nnow shalt thou be moved. Give me a cup of sack to\nmake my eyes look red, that it may be thought I have\nwept; for I must speak in passion, and I will do it\nin King Cambyses' vein.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Well, here is my leg.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "And here is my speech. Stand aside, nobility.\n", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "O Jesu, this is excellent sport, i' faith!\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Weep not, sweet queen; for trickling tears are vain.\n", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "O, the father, how he holds his countenance!\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "For God's sake, lords, convey my tristful queen;\nFor tears do stop the flood-gates of her eyes.\n", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "O Jesu, he doth it as like one of these harlotry\nplayers as ever I see!\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Peace, good pint-pot; peace, good tickle-brain.\nHarry, I do not only marvel where thou spendest thy\ntime, but also how thou art accompanied: for though\nthe camomile, the more it is trodden on the faster\nit grows, yet youth, the more it is wasted the\nsooner it wears. That thou art my son, I have\npartly thy mother's word, partly my own opinion,\nbut chiefly a villanous trick of thine eye and a\nfoolish-hanging of thy nether lip, that doth warrant\nme. If then thou be son to me, here lies the point;\nwhy, being son to me, art thou so pointed at? Shall\nthe blessed sun of heaven prove a micher and eat\nblackberries? a question not to be asked. Shall\nthe sun of England prove a thief and take purses? a\nquestion to be asked. There is a thing, Harry,\nwhich thou hast often heard of and it is known to\nmany in our land by the name of pitch: this pitch,\nas ancient writers do report, doth defile; so doth\nthe company thou keepest: for, Harry, now I do not\nspeak to thee in drink but in tears, not in\npleasure but in passion, not in words only, but in\nwoes also: and yet there is a virtuous man whom I\nhave often noted in thy company, but I know not his name.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What manner of man, an it like your majesty?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "A goodly portly man, i' faith, and a corpulent; of a\ncheerful look, a pleasing eye and a most noble\ncarriage; and, as I think, his age some fifty, or,\nby'r lady, inclining to three score; and now I\nremember me, his name is Falstaff: if that man\nshould be lewdly given, he deceiveth me; for, Harry,\nI see virtue in his looks. If then the tree may be\nknown by the fruit, as the fruit by the tree, then,\nperemptorily I speak it, there is virtue in that\nFalstaff: him keep with, the rest banish. And tell\nme now, thou naughty varlet, tell me, where hast\nthou been this month?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Dost thou speak like a king? Do thou stand for me,\nand I'll play my father.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Depose me? if thou dost it half so gravely, so\nmajestically, both in word and matter, hang me up by\nthe heels for a rabbit-sucker or a poulter's hare.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Well, here I am set.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "And here I stand: judge, my masters.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Now, Harry, whence come you?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "My noble lord, from Eastcheap.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "The complaints I hear of thee are grievous.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "'Sblood, my lord, they are false: nay, I'll tickle\nye for a young prince, i' faith.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Swearest thou, ungracious boy? henceforth ne'er look\non me. Thou art violently carried away from grace:\nthere is a devil haunts thee in the likeness of an\nold fat man; a tun of man is thy companion. Why\ndost thou converse with that trunk of humours, that\nbolting-hutch of beastliness, that swollen parcel\nof dropsies, that huge bombard of sack, that stuffed\ncloak-bag of guts, that roasted Manningtree ox with\nthe pudding in his belly, that reverend vice, that\ngrey iniquity, that father ruffian, that vanity in\nyears? Wherein is he good, but to taste sack and\ndrink it? wherein neat and cleanly, but to carve a\ncapon and eat it? wherein cunning, but in craft?\nwherein crafty, but in villany? wherein villanous,\nbut in all things? wherein worthy, but in nothing?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "I would your grace would take me with you: whom\nmeans your grace?\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "That villanous abominable misleader of youth,\nFalstaff, that old white-bearded Satan.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "My lord, the man I know.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I know thou dost.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "But to say I know more harm in him than in myself,\nwere to say more than I know. That he is old, the\nmore the pity, his white hairs do witness it; but\nthat he is, saving your reverence, a whoremaster,\nthat I utterly deny. If sack and sugar be a fault,\nGod help the wicked! if to be old and merry be a\nsin, then many an old host that I know is damned: if\nto be fat be to be hated, then Pharaoh's lean kine\nare to be loved. No, my good lord; banish Peto,\nbanish Bardolph, banish Poins: but for sweet Jack\nFalstaff, kind Jack Falstaff, true Jack Falstaff,\nvaliant Jack Falstaff, and therefore more valiant,\nbeing, as he is, old Jack Falstaff, banish not him\nthy Harry's company, banish not him thy Harry's\ncompany: banish plump Jack, and banish all the world.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I do, I will.\nA knocking heard", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exeunt Hostess, FRANCIS, and BARDOLPH", line_order: 5, scene_id: scene_id},
  {character: '', line: "Re-enter BARDOLPH, running", line_order: 5, scene_id: scene_id},
  {character: 'BARDOLPH', line: "O, my lord, my lord! the sheriff with a most\nmonstrous watch is at the door.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Out, ye rogue! Play out the play: I have much to\nsay in the behalf of that Falstaff.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Re-enter the Hostess", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "O Jesu, my lord, my lord!\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Heigh, heigh! the devil rides upon a fiddlestick:\nwhat's the matter?\n", line_order: 5, scene_id: scene_id},
  {character: 'Hostess', line: "The sheriff and all the watch are at the door: they\nare come to search the house. Shall I let them in?\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Dost thou hear, Hal? never call a true piece of\ngold a counterfeit: thou art essentially mad,\nwithout seeming so.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "And thou a natural coward, without instinct.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "I deny your major: if you will deny the sheriff,\nso; if not, let him enter: if I become not a cart\nas well as another man, a plague on my bringing up!\nI hope I shall as soon be strangled with a halter as another.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Go, hide thee behind the arras: the rest walk up\nabove. Now, my masters, for a true face and good\nconscience.\n", line_order: 5, scene_id: scene_id},
  {character: 'FALSTAFF', line: "Both which I have had: but their date is out, and\ntherefore I'll hide me.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Call in the sheriff.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exeunt all except PRINCE HENRY and PETO", line_order: 5, scene_id: scene_id},
  {character: '', line: "Enter Sheriff and the Carrier", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Now, master sheriff, what is your will with me?\n", line_order: 5, scene_id: scene_id},
  {character: 'Sheriff', line: "First, pardon me, my lord. A hue and cry\nHath follow'd certain men unto this house.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What men?", line_order: 5, scene_id: scene_id},
  {character: 'Sheriff', line: "One of them is well known, my gracious lord,\nA gross fat man.\n", line_order: 5, scene_id: scene_id},
  {character: 'Carrier', line: "As fat as butter.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "The man, I do assure you, is not here;\nFor I myself at this time have employ'd him.\nAnd, sheriff, I will engage my word to thee\nThat I will, by to-morrow dinner-time,\nSend him to answer thee, or any man,\nFor any thing he shall be charged withal:\nAnd so let me entreat you leave the house.\n", line_order: 5, scene_id: scene_id},
  {character: 'Sheriff', line: "I will, my lord. There are two gentlemen\nHave in this robbery lost three hundred marks.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "It may be so: if he have robb'd these men,\nHe shall be answerable; and so farewell.\n", line_order: 5, scene_id: scene_id},
  {character: 'Sheriff', line: "Good night, my noble lord.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "I think it is good morrow, is it not?\n", line_order: 5, scene_id: scene_id},
  {character: 'Sheriff', line: "Indeed, my lord, I think it be two o'clock.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exeunt Sheriff and Carrier", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "This oily rascal is known as well as Paul's. Go,\ncall him forth.\n", line_order: 5, scene_id: scene_id},
  {character: 'PETO', line: "Falstaff!--Fast asleep behind the arras, and\nsnorting like a horse.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Hark, how hard he fetches breath. Search his pockets.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "He searcheth his pockets, and findeth certain papers", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "What hast thou found?\n", line_order: 5, scene_id: scene_id},
  {character: 'PETO', line: "Nothing but papers, my lord.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "Let's see what they be: read them.\n", line_order: 5, scene_id: scene_id},
  {character: 'PETO', line: "[Reads]  Item, A capon,. . 2s. 2d.\n Item, Sauce,. . . 4d.\n Item, Sack, two gallons, 5s. 8d.\n Item, Anchovies and sack after supper, 2s. 6d.\nItem, Bread, ob.\n", line_order: 5, scene_id: scene_id},
  {character: 'PRINCE HENRY', line: "O monstrous! but one half-penny-worth of bread to\nthis intolerable deal of sack! What there is else,\nkeep close; we'll read it at more advantage: there\nlet him sleep till day. I'll to the court in the\nmorning. We must all to the wars, and thy place\nshall be honourable. I'll procure this fat rogue a\ncharge of foot; and I know his death will be a\nmarch of twelve-score. The money shall be paid\nback again with advantage. Be with me betimes in\nthe morning; and so, good morrow, Peto.\n", line_order: 5, scene_id: scene_id},
  {character: '', line: "Exeunt", line_order: 5, scene_id: scene_id},
  {character: 'PETO', line: "Good morrow, good my lord.\n", line_order: 5, scene_id: scene_id},  
]
# add line order
line_order = 0
lines.each do |line|
  line[:line_order] = line_order
  Line.create(line)
  line_order += 1
end
# create test user
User.create(:email => "test@test.com", :password => "password")

